name: openai-proxy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - fastapi>=0.110.0
  - uvicorn>=0.27.0
  - httpx>=0.27.0
  - redis-py>=5.0.0  # aioredis alternative that works better with conda
  - pydantic>=2.8.0
  - python-dotenv>=1.0.0
  - structlog>=23.2.0
  - prometheus_client>=0.20.0
  - pip:
    - pydantic-settings>=2.4.0
    - slowapi>=0.1.9
    - aioredis>=2.0.1